name: GCC Actions Test branchone

on: push

jobs:
  debug-context:
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub Context
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Ref Name: ${{ github.ref_name }}"
        echo "Repository: ${{ github.repository }}"

  build-branchone:
    if: github.ref == 'refs/heads/branchone'

    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v3

    - name: branch one build
      run: |
           echo "Hello World from branchone"
           g++ -std=c++20 main.cpp -o main.out
           ./main.out
      shell: bash
