name: GCC Actions Test

on: push

jobs:
#  debug-context:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Print GitHub Context
#      run: |
#        echo "GitHub Ref: ${{ github.ref }}"
#        echo "GitHub Ref Name: ${{ github.ref_name }}"
#        echo "Repository: ${{ github.repository }}"

#  build-test:
#    if: github.ref == 'refs/heads/main'
#
#    runs-on: ubuntu-24.04-arm
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Build the main.cpp with g++ -std=c++20
#      run: g++ -std=c++20 main.cpp -o main.out
#      shell: bash
#
#  build-docker-image-push:
#    needs: build-test
#    runs-on: ubuntu-24.04-arm
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Compile the cpp and build the image with finished product and push it into docker repo
#      run: |
#           #apt-get update
#           #apt install -y g++
#           #g++ -std=c++20 main.cpp -o main.out
#           #./main.out
#           docker build -t schd1337/githubactions:latest .
#           echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#           docker push schd1337/githubactions:latest
#      shell: bash

  ssh-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into server and echo hello world
      run: |
            echo "${{ secrets.EC2_KEY }}" | tee $PWD/ec2.pem
            chmod 600 $PWD/ec2.pem
            ls -l
            pwd
            uname -a
            hostname
            ssh -tt -o "StrictHostKeyChecking=no" -i "ec2.pem" admin@ec2-13-126-108-250.ap-south-1.compute.amazonaws.com << EOF
            pwd
            hostname
            uname -a
            echo $HOSTNAME | tee $HOME/sshdone.txt
            ls -l
            EOF
      shell: bash