name: GCC Actions Test

on: [push]

jobs:
  build-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the main.cpp with g++ -std=c++20
      run: g++ -std=c++20 main.cpp -o main.out
      shell: bash

  build-docker-image-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile the cpp and build the image with finished product and push it into docker repo
      run: |
           g++ -std=c++20 main.cpp -o main.out
           docker build -t schd1337/githubactions:latest .
           echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
           docker push schd1337/githubactions:latest
      shell: bash
