name: GCC Actions Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the main.cpp with g++ -std=c++20
      run: |
           sudo apt-get update
           sudo apt install gcc
           g++ -std=c++20 main.cpp -o main.out
      shell: bash

#  run:
#    runs-on: ubuntu-latest

    - name: Run the main.out
      run: ./main.out
      shell: bash
